"""GitHub repository initialization and auto-commit helper.

Used by the DevOps pipeline to persist generated project files into a
fresh git repository and, optionally, push them to a remote.
"""

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess


# Resolve the absolute path to git once
_GIT_PATH = shutil.which("git") or "git"


def init_repo(directory: Path, repo_url: str | None = None) -> None:
    """Initialize a git repository in the given directory.

    If the directory does not yet exist it is created. When ``repo_url`` is
    provided the remote ``origin`` is added after initialisation.

    Args:
        directory: Path to the directory to initialise as a git repository.
        repo_url: Optional HTTPS or SSH URL to add as the ``origin`` remote.

    Raises:
        subprocess.CalledProcessError: If any git command fails.
    """
    directory.mkdir(parents=True, exist_ok=True)
    # Using the resolved path fixes S607
    subprocess.run(  # noqa: S603
        [_GIT_PATH, "init"], cwd=directory, check=True, capture_output=True
    )

    if repo_url:
        subprocess.run(  # noqa: S603
            [_GIT_PATH, "remote", "add", "origin", repo_url],
            cwd=directory,
            check=True,
            capture_output=True,
        )


def auto_commit(
    directory: Path,
    message: str = "chore: auto-generated by JAME",
) -> None:
    """Stage all files and create a commit in the given repository.

    Args:
        directory: Path to an initialised git repository.
        message: Commit message to use.

    Raises:
        subprocess.CalledProcessError: If ``git add`` or ``git commit`` fails.
    """
    subprocess.run(  # noqa: S603
        [_GIT_PATH, "add", "-A"], cwd=directory, check=True, capture_output=True
    )
    subprocess.run(  # noqa: S603
        [_GIT_PATH, "commit", "-m", message],
        cwd=directory,
        check=True,
        capture_output=True,
    )


def push(directory: Path, remote: str = "origin", branch: str = "main") -> None:
    """Push the current branch to the specified remote.

    Args:
        directory: Path to the git repository.
        remote: Name of the remote to push to (default: ``"origin"``).
        branch: Branch name to push (default: ``"main"``).

    Raises:
        subprocess.CalledProcessError: If ``git push`` fails.
    """
    subprocess.run(  # noqa: S603
        [_GIT_PATH, "push", remote, branch],
        cwd=directory,
        check=True,
        capture_output=True,
    )
