"""Shared utilities for all agent nodes."""

from __future__ import annotations

import json
from pathlib import Path
import re

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import HumanMessage

from integrations.github import auto_commit, init_repo


# ---------------------------------------------------------------------------
# Artifact saving
# ---------------------------------------------------------------------------


def save_artifacts(state: dict, output_dir: Path | str = "output") -> Path:
    """Write all pipeline artifacts to *output_dir*.

    Saves specs, diagrams, generated source files, CI/CD YAML, Docker files,
    Python tooling files (.gitignore, Makefile, pyproject.toml, etc.),
    and the reasoning trace.  When a CI/CD workflow is present the output
    project directory is also initialised as a git repository.

    Args:
        state: Final ``AgentState`` dict (or any dict with the same keys).
        output_dir: Root directory for all saved files. Defaults to ``output/``.

    Returns:
        The ``project/`` sub-directory path where source files were written.
    """
    output_path = Path(output_dir)
    project_dir = output_path / "project"
    output_path.mkdir(parents=True, exist_ok=True)
    project_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 60)
    print("💾 SAVING ARTIFACTS")
    print("=" * 60)

    # ── Specs & diagrams ───────────────────────────────────────
    if specs := state.get("specs", ""):
        (output_path / "specifications.md").write_text(specs, encoding="utf-8")
        print("  📋 Specs     → output/specifications.md")

    if diagrams := state.get("diagrams", ""):
        (output_path / "c4_diagrams.md").write_text(diagrams, encoding="utf-8")
        print("  📐 Diagrams  → output/c4_diagrams.md")

    # ── Source files ───────────────────────────────────────────
    code_files = state.get("code_files", [])
    saved = 0
    for f in code_files:
        # Support both Pydantic CodeFile objects and plain dicts.
        raw_path = f["path"] if isinstance(f, dict) else f.path
        content = f["content"] if isinstance(f, dict) else f.content
        if not raw_path:
            continue
        dest = project_dir / raw_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  📄 Code      → output/project/{raw_path}")
        saved += 1
    if saved:
        print(f"  📦 Total     → {saved} source files saved")

    # ── CI files (workflow, requirements, tooling, gitignore…) ─
    ci_saved = 0
    for f in state.get("ci_files", []):
        raw_path = f["path"] if isinstance(f, dict) else f.path
        content = f["content"] if isinstance(f, dict) else f.content
        if not raw_path or not content:
            continue
        dest = project_dir / raw_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  🔧 CI        → output/project/{raw_path}")
        ci_saved += 1

    # ── CD files (Dockerfile, compose, env, dockerignore…) ─────
    cd_saved = 0
    for f in state.get("cd_files", []):
        raw_path = f["path"] if isinstance(f, dict) else f.path
        content = f["content"] if isinstance(f, dict) else f.content
        if not raw_path or not content:
            continue
        dest = project_dir / raw_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  🐳 CD        → output/project/{raw_path}")
        cd_saved += 1

    # ── QA issues ──────────────────────────────────────────────
    if qa_issues := state.get("qa_issues", []):
        serializable = [
            i if isinstance(i, dict) else i.model_dump() for i in qa_issues
        ]
        (output_path / "qa_issues.json").write_text(
            json.dumps(serializable, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print("  🎫 QA Issues → output/qa_issues.json")

    # ── Git init — always create a repo for the generated project ──
    try:
        init_repo(project_dir)
        auto_commit(
            project_dir,
            message="chore: initial project scaffold (generated by JAME)",
        )
        print("  🗂️  Git       → output/project/ initialized with first commit")
    except Exception as exc:
        print(f"  ⚠️  Git init failed: {exc}")

    # ── Reasoning trace ────────────────────────────────────────
    if logs := state.get("reasoning_logs", []):
        (output_path / "reasoning_trace.json").write_text(
            json.dumps(logs, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print("  🧠 Trace     → output/reasoning_trace.json")

    return project_dir


COMPRESS_THRESHOLD = 5000


def strip_thinking(text: str) -> tuple[str, str]:
    """Extract <think>…</think> blocks produced by reasoning models.

    Args:
        text: Raw LLM response string.

    Returns:
        A (thinking, content) tuple. ``thinking`` is empty if no block found.
    """
    if "<think>" in text and "</think>" in text:
        thinking = text.split("<think>")[1].split("</think>")[0].strip()
        content = text.split("</think>", 1)[-1].strip()
        return thinking, content
    return "", text


def parse_json_safe(raw: str, fallback: dict | None = None) -> dict:
    """Extract JSON from an LLM response, stripping markdown fences if present.

    Tries a direct parse first, then falls back to regex extraction.

    Args:
        raw: Raw LLM response string.
        fallback: Value to return if no valid JSON is found. Defaults to ``{}``.

    Returns:
        Parsed dict, or ``fallback`` if parsing fails.
    """
    if fallback is None:
        fallback = {}
    raw = raw.strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    return fallback


def compress(llm: BaseChatModel, context: str, prompt_template: str) -> str:
    """Compress a context string using the LLM.

    Args:
        llm: The language model to use.
        context: The context string to compress.
        prompt_template: A format string with a ``{context}`` placeholder.

    Returns:
        Compressed context string.
    """
    print("[MEMORY] Context too large — compressing …")
    resp = llm.invoke(
        [HumanMessage(content=prompt_template.format(context=context))]
    )
    _, compressed = strip_thinking(resp.content)
    print("[MEMORY] Compressed.\n")
    return compressed


def maybe_compress(
    llm: BaseChatModel,
    new_context: str,
    memory: str,
    prompt_template: str,
    threshold: int = COMPRESS_THRESHOLD,
) -> str:
    """Compress only when the combined memory + new context exceeds the threshold.

    Args:
        llm: The language model to use.
        new_context: Newly produced context to append.
        memory: Existing memory string.
        prompt_template: A format string with a ``{context}`` placeholder.
        threshold: Character count above which compression is triggered.

    Returns:
        Updated memory string, compressed if necessary.
    """
    full = (memory + "\n\n" + new_context).strip()
    return (
        compress(llm, full, prompt_template) if len(full) > threshold else full
    )
