#!/usr/bin/env python3
"""Multi-Agent Software Factory — CLI entry point.

Usage:
    python main.py                                        # interactive prompt
    python main.py "A FastAPI Task Manager"               # direct input
    python main.py --input input/spec.md                  # load specs from file
    python main.py --input input/spec.md --github         # create GitHub repo (auto-named)
    python main.py --input input/spec.md --github my-repo # create GitHub repo (named)
    python main.py --input input/spec.md --github --private  # private repo
    python main.py --input input/simple_function_specifications.md --github 
"""




from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

from dotenv import load_dotenv

# Ensure the parent directory is in the path for relative imports
sys.path.insert(0, str(Path(__file__)/ "agents"))

from graph import build_graph
from state import AgentState


OUTPUT_DIR = Path("output")
PROJECT_DIR = OUTPUT_DIR / "project"


def _slugify(text: str) -> str:
    """Convert free-form text into a valid GitHub repository name."""
    slug = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')
    return slug[:100] or "jame-project"


def _create_github_repo(project_dir: Path, repo_name: str, private: bool = False) -> None:
    """Create a GitHub remote repository and push the local project to it."""
    visibility = "--private" if private else "--public"
    try:
        subprocess.run(["gh", "--version"], check=True, capture_output=True)
    except FileNotFoundError:
        print("  ⚠️  GitHub CLI (gh) not found.")
        print("     Install it: https://cli.github.com")
        print(f"     Then run manually:")
        print(f"       gh repo create {repo_name} {visibility} --source {project_dir} --push")
        return

    print(f"  🐙 GitHub    → Creating repository '{repo_name}' ({visibility.lstrip('--')}) …")
    try:
        subprocess.run(
            ["gh", "repo", "create", repo_name, visibility, "--source", ".", "--push"],
            cwd=project_dir, check=True,
        )
        print(f"  🐙 GitHub    → https://github.com/$(gh api user -q .login)/{repo_name}")
    except subprocess.CalledProcessError:
        print("  ⚠️  GitHub repo creation failed. Check that you are authenticated:")
        print("       gh auth login")


def _init_git_repo(project_dir: Path) -> None:
    """Initialize a git repository in the generated project directory with a first commit."""
    git_env = {
        **os.environ,
        "GIT_AUTHOR_NAME":     "JAME",
        "GIT_AUTHOR_EMAIL":    "jame@generated",
        "GIT_COMMITTER_NAME":  "JAME",
        "GIT_COMMITTER_EMAIL": "jame@generated",
    }
    try:
        subprocess.run(["git", "init", "-b", "main"], cwd=project_dir, check=True, capture_output=True)
        subprocess.run(["git", "add", "."],           cwd=project_dir, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", "chore: initial project scaffold (generated by JAME)"],
            cwd=project_dir, check=True, capture_output=True, env=git_env,
        )
    except subprocess.CalledProcessError as exc:
        print(f"  ⚠️  Git init failed: {exc.stderr.decode().strip()}")
    except FileNotFoundError:
        print("  ⚠️  git not found — skipping repository initialization.")


def _sanitize_file_path(raw_path: str) -> str:
    """Clean a file path of markdown artefacts before writing to disk."""
    path = re.sub(r'[#*`]', '', raw_path)
    path = re.sub(r'^\s*[\d]+\.\s*', '', path)
    path = re.sub(r'^\s*[-•]\s*', '', path)
    path = path.strip().strip('"').strip("'")
    path = re.sub(r'^\./', '', path)
    path = re.sub(r'[<>"|?*]', '', path)
    return path


def save_artifacts(final_state: dict) -> None:
    """Write all generated artifacts to the output/ directory."""

    OUTPUT_DIR.mkdir(exist_ok=True)
    PROJECT_DIR.mkdir(exist_ok=True)

    # ── Save diagrams ──────────────────────────────────────────
    diagrams = final_state.get("diagrams", "")
    if diagrams:
        (OUTPUT_DIR / "c4_diagrams.md").write_text(diagrams, encoding="utf-8")
        print("  📐 Diagrams  → output/c4_diagrams.md")

    # ── Save specs ─────────────────────────────────────────────
    specs = final_state.get("specs", "")
    if specs:
        (OUTPUT_DIR / "specifications.md").write_text(specs, encoding="utf-8")
        print("  📋 Specs     → output/specifications.md")

    # ── Save code files ────────────────────────────────────────
    code_files = final_state.get("code_files", [])
    saved_count = 0
    for f in code_files:
        clean_path = _sanitize_file_path(f["path"])
        if not clean_path:
            print(f"  ⚠️  Skipping file with invalid path: {f['path']!r}")
            continue
        file_path = PROJECT_DIR / clean_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(f["content"], encoding="utf-8")
        print(f"  📄 Code      → output/project/{clean_path}")
        saved_count += 1

    if code_files:
        print(f"  📦 Total     → {saved_count} files saved to output/project/")

    # ── Save CI files (workflow, requirements, tooling…) ───────
    ci_saved = 0
    for f in final_state.get("ci_files", []):
        path, content = f["path"], f["content"]
        if not path or not content:
            continue
        dest = PROJECT_DIR / path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  🔧 CI        → output/project/{path}")
        ci_saved += 1

    # ── Save CD files (Dockerfile, compose, env…) ──────────────
    for f in final_state.get("cd_files", []):
        path, content = f["path"], f["content"]
        if not path or not content:
            continue
        dest = PROJECT_DIR / path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  🐳 CD        → output/project/{path}")

    # ── Initialize git repository when CI was generated ────────
    if ci_saved:
        _init_git_repo(PROJECT_DIR)
        print("  🗂️  Git      → output/project/ initialized with first commit")

    # ── Save reasoning trace ───────────────────────────────────
    logs = final_state.get("reasoning_logs", [])
    if logs:
        (OUTPUT_DIR / "reasoning_trace.json").write_text(
            json.dumps(logs, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print("  🧠 Trace     → output/reasoning_trace.json")


def print_reasoning_summary(final_state: dict) -> None:
    """Print a compact reasoning summary at the end."""
    logs = final_state.get("reasoning_logs", [])
    if not logs:
        return

    print("\n" + "=" * 60)
    print("🧠 REASONING TRACE SUMMARY")
    print("=" * 60)

    for entry in logs:
        phase_icon = {"plan": "📋", "act": "⚡", "reason": "💭"}.get(entry["phase"], "•")
        print(f"  {phase_icon} [{entry['agent'].upper():>10}] {entry['phase'].upper():>6}: {entry['content']}")


def main() -> None:
    load_dotenv()

    if not os.getenv("SNOWFLAKE_API_KEY"):
        print("❌ Error: SNOWFLAKE_API_KEY not found.")
        print("   Copy .env.example to .env and add your Snowflake Cortex credentials.")
        sys.exit(1)

    # ── Parse flags ────────────────────────────────────────────
    specs_from_file = ""
    github_repo_name: str | None = None
    github_private = False
    args = sys.argv[1:]

    if "--private" in args:
        github_private = True
        args.remove("--private")

    if "--github" in args:
        idx = args.index("--github")
        # Accept optional repo name as the next positional argument
        if idx + 1 < len(args) and not args[idx + 1].startswith("--"):
            github_repo_name = args[idx + 1]
            args = args[:idx] + args[idx + 2:]
        else:
            github_repo_name = ""   # auto-derive from user_request after parsing
            args = args[:idx] + args[idx + 1:]

    # ── Parse --input flag ─────────────────────────────────────
    if "--input" in args:
        idx = args.index("--input")
        if idx + 1 >= len(args):
            print("❌ Error: --input requires a file path argument.")
            sys.exit(1)
        input_path = Path(args[idx + 1])
        if not input_path.is_absolute():
            input_path = Path(__file__).parent / input_path
        if not input_path.exists():
            print(f"❌ Error: Input file not found: {input_path}")
            sys.exit(1)
        specs_from_file = input_path.read_text(encoding="utf-8")
        print(f"📂 Loaded specs from: {input_path.name}")
        args = args[:idx] + args[idx + 2:]

    # ── Get user request ───────────────────────────────────────
    if args:
        user_request = " ".join(args)
    elif specs_from_file:
        user_request = f"Build from specifications file"
    else:
        print("🏭 Multi-Agent Software Factory")
        print("─" * 40)
        user_request = input("Describe the application to build:\n> ").strip()
        if not user_request:
            print("No input provided. Exiting.")
            sys.exit(0)

    # Auto-derive repo name from user_request if --github was given without a name
    if github_repo_name == "":
        github_repo_name = _slugify(user_request)

    print(f"\n🚀 Starting pipeline for: \"{user_request}\"\n")

    # ── Build and run the graph ────────────────────────────────
    graph = build_graph()

    initial_state: AgentState = {
        "user_request":   user_request,
        "specs":          specs_from_file,
        "diagrams":       "",
        "code_files":     [],
        "ci_files":       [],
        "cd_files":       [],
        "needs_ci":       False,
        "needs_cd":       False,
        "qa_passed":      False,
        "qa_feedback":    "",
        "qa_issues":      [],
        "iteration":      0,
        "max_iterations": 2,
        "reasoning_logs": [],
    }

    final_state = graph.invoke(initial_state)

    # ── Save everything ────────────────────────────────────────
    print("\n" + "=" * 60)
    print("💾 SAVING ARTIFACTS")
    print("=" * 60)
    save_artifacts(final_state)

    # ── Push to GitHub (if requested) ──────────────────────────
    if github_repo_name is not None:
        _create_github_repo(PROJECT_DIR, github_repo_name, private=github_private)

    # ── Summary ────────────────────────────────────────────────
    print_reasoning_summary(final_state)

if __name__ == "__main__":
    main()
